<?php

namespace Modules\Home;

class AcfFields extends \Modules\Acf\AcfFields
{
    public function acfFields(): void
    {
        acf_add_local_field_group(array(
            'key' => 'group_6383b4f387797',
            'title' => 'Home',
            'fields' => array(
                array(
                    'key' => 'field_6383bd36e0bf8',
                    'label' => 'Home',
                    'name' => 'home',
                    'aria-label' => '',
                    'type' => 'group',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'layout' => 'block',
                    'sub_fields' => array(
                        array(
                            'key' => 'field_6383b4f3d444e',
                            'label' => 'Video Section',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_6383be51e0bf9',
                            'label' => 'Video Fields',
                            'name' => 'video',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6383be8be0bfa',
                                    'label' => 'Show Video',
                                    'name' => 'show',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                    'ui' => 1,
                                ),
                                array(
                                    'key' => 'field_6383be8fe0bfb',
                                    'label' => 'Video Url',
                                    'name' => 'url',
                                    'aria-label' => '',
                                    'type' => 'oembed',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'width' => '',
                                    'height' => '',
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6383b6b829544',
                            'label' => 'Welcome Section',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_6383bf4e1f5bc',
                            'label' => 'Welcome Fields',
                            'name' => 'welcome',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6383c3476a5e0',
                                    'label' => 'Show',
                                    'name' => 'show',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                    'ui' => 1,
                                ),
                                array(
                                    'key' => 'field_6383b6fd29545',
                                    'label' => 'Title',
                                    'name' => 'title',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_6383b76029546',
                                    'label' => 'Subtitle',
                                    'name' => 'subtitle',
                                    'aria-label' => '',
                                    'type' => 'text',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'default_value' => '',
                                    'maxlength' => '',
                                    'placeholder' => '',
                                    'prepend' => '',
                                    'append' => '',
                                ),
                                array(
                                    'key' => 'field_6383b790dabaa',
                                    'label' => 'Reasons',
                                    'name' => 'reasons',
                                    'aria-label' => '',
                                    'type' => 'repeater',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'layout' => 'table',
                                    'pagination' => 0,
                                    'min' => 0,
                                    'max' => 0,
                                    'collapsed' => 'field_6383b832dabac',
                                    'button_label' => 'Add Row',
                                    'rows_per_page' => 20,
                                    'sub_fields' => array(
                                        array(
                                            'key' => 'field_6383b855dabad',
                                            'label' => 'Show',
                                            'name' => 'show',
                                            'aria-label' => '',
                                            'type' => 'true_false',
                                            'instructions' => '',
                                            'required' => 0,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'message' => '',
                                            'default_value' => 0,
                                            'ui_on_text' => '',
                                            'ui_off_text' => '',
                                            'ui' => 1,
                                            'parent_repeater' => 'field_6383b790dabaa',
                                        ),
                                        array(
                                            'key' => 'field_6383b7e0dabab',
                                            'label' => 'Icon',
                                            'name' => 'icon',
                                            'aria-label' => '',
                                            'type' => 'image',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'return_format' => 'id',
                                            'library' => 'all',
                                            'min_width' => '',
                                            'min_height' => '',
                                            'min_size' => '',
                                            'max_width' => '',
                                            'max_height' => '',
                                            'max_size' => '',
                                            'mime_types' => '.svg',
                                            'preview_size' => 'thumbnail',
                                            'parent_repeater' => 'field_6383b790dabaa',
                                        ),
                                        array(
                                            'key' => 'field_6383b832dabac',
                                            'label' => 'Label',
                                            'name' => 'label',
                                            'aria-label' => '',
                                            'type' => 'text',
                                            'instructions' => '',
                                            'required' => 1,
                                            'conditional_logic' => 0,
                                            'wrapper' => array(
                                                'width' => '',
                                                'class' => '',
                                                'id' => '',
                                            ),
                                            'default_value' => '',
                                            'maxlength' => '',
                                            'placeholder' => '',
                                            'prepend' => '',
                                            'append' => '',
                                            'parent_repeater' => 'field_6383b790dabaa',
                                        ),
                                    ),
                                ),
                            ),
                        ),
                        array(
                            'key' => 'field_6383b8de92dbb',
                            'label' => 'Event Section',
                            'name' => '',
                            'aria-label' => '',
                            'type' => 'tab',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'placement' => 'left',
                            'endpoint' => 0,
                        ),
                        array(
                            'key' => 'field_6383bfb51f5bd',
                            'label' => 'Event Fields',
                            'name' => 'events',
                            'aria-label' => '',
                            'type' => 'group',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'layout' => 'block',
                            'sub_fields' => array(
                                array(
                                    'key' => 'field_6383b8f392dbc',
                                    'label' => 'Show Specific Events',
                                    'name' => 'show_specific',
                                    'aria-label' => '',
                                    'type' => 'true_false',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => 0,
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'message' => '',
                                    'default_value' => 0,
                                    'ui_on_text' => '',
                                    'ui_off_text' => '',
                                    'ui' => 1,
                                ),
                                array(
                                    'key' => 'field_6383b93992dbd',
                                    'label' => 'Events',
                                    'name' => 'list',
                                    'aria-label' => '',
                                    'type' => 'relationship',
                                    'instructions' => '',
                                    'required' => 0,
                                    'conditional_logic' => array(
                                        array(
                                            array(
                                                'field' => 'field_6383b8f392dbc',
                                                'operator' => '==',
                                                'value' => '1',
                                            ),
                                        ),
                                    ),
                                    'wrapper' => array(
                                        'width' => '',
                                        'class' => '',
                                        'id' => '',
                                    ),
                                    'post_type' => array(
                                        0 => 'post',
                                    ),
                                    'taxonomy' => '',
                                    'filters' => array(
                                        0 => 'search',
                                        1 => 'taxonomy',
                                    ),
                                    'return_format' => 'id',
                                    'min' => '',
                                    'max' => '',
                                    'elements' => array(
                                        0 => 'featured_image',
                                    ),
                                ),
                            ),
                        ),
                    ),
                ),
            ),
            'location' => array(
                array(
                    array(
                        'param' => 'options_page',
                        'operator' => '==',
                        'value' => 'acf-options',
                    ),
                ),
            ),
            'menu_order' => 0,
            'position' => 'normal',
            'style' => 'default',
            'label_placement' => 'top',
            'instruction_placement' => 'label',
            'hide_on_screen' => '',
            'active' => true,
            'description' => '',
            'show_in_rest' => 0,
        ));
    }
}
